# Generated by Django 5.1.4 on 2025-03-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Texto:'),
        ),
    ]
