# Generated by Django 5.1.4 on 2025-02-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_contact', '0002_remove_contactemail_is_activate_formcontactemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontactemail',
            name='is_activate',
            field=models.BooleanField(default=False, verbose_name='Está ativado'),
        ),
    ]
