# Generated by Django 5.1.4 on 2025-01-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_plans'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plans',
            options={'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(choices=[('GRÁTIS', 'Grátis'), ('CONEXÃO', 'Conexão'), ('INFLUÊNCIA', 'Influência')], default='GRÁTIS', max_length=50),
        ),
    ]
