# Generated by Django 5.1.4 on 2025-01-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plans_options_alter_plans_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
