# Generated by Django 5.1.4 on 2025-01-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plans_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.plans'),
        ),
    ]
