# Generated by Django 5.1.4 on 2025-02-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0003_alter_userprofile_created_at_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_of_use_is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
