# Generated by Django 5.1.4 on 2025-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0004_userprofile_terms_of_use_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='terms_of_use_is_ready',
            field=models.BooleanField(default=False, verbose_name='Termos de uso foi lido'),
        ),
    ]
