# Generated by Django 5.1.4 on 2025-02-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0005_alter_userprofile_terms_of_use_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome de usuário'),
        ),
    ]
