# Generated by Django 5.1.4 on 2025-01-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Usuário:'),
        ),
        migrations.AlterField(
            model_name='link',
            name='social_network',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rede social'),
        ),
    ]
