# Generated by Django 5.1.4 on 2025-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_link_icon_link_is_profile_link_link_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='og_image',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem da Capa:'),
        ),
    ]
