# Generated by Django 5.1.4 on 2025-03-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_link_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='social_network',
            field=models.TextField(blank=True, null=True, verbose_name='Rede social'),
        ),
    ]
