# Generated by Django 5.1.4 on 2025-03-08 23:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0007_alter_link_social_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='URL do ícone:'),
        ),
        migrations.AlterField(
            model_name='link',
            name='og_image',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='Imagem da Capa:'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='URL:'),
        ),
    ]
