# Generated by Django 5.1.4 on 2025-02-09 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='action',
            field=models.TextField(verbose_name='Interação'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data/hora'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
