# Generated by Django 5.1.4 on 2025-01-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='product_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
