# Generated by Django 5.1.4 on 2025-01-06 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0003_profile_link_count_profile_product_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='link_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='product_count',
        ),
    ]
