# Generated by Django 5.1.4 on 2025-01-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('route', 'month', 'year')},
            },
        ),
    ]
