# Generated by Django 5.1.4 on 2025-01-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analyticprofile_analytic_analyticprofileviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytic',
            name='month',
            field=models.PositiveSmallIntegerField(verbose_name='Mês de criação'),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='route',
            field=models.CharField(max_length=255, verbose_name='Rota de perfil'),
        ),
        migrations.AlterField(
            model_name='analytic',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ano de criação'),
        ),
    ]
