# Generated by Django 5.1.4 on 2025-01-20 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_analytic_month_alter_analytic_route_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticprofileviews',
            name='number',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='analyticprofileviews',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
