# Generated by Django 5.1.4 on 2025-02-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_analyticprofileviewsperdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'verbose_name': 'Análise', 'verbose_name_plural': 'Análises'},
        ),
        migrations.AlterModelOptions(
            name='analyticprofileviews',
            options={'ordering': ['-number'], 'verbose_name': 'Análise de visualização do perfil', 'verbose_name_plural': 'Análises de visualizações de perfis'},
        ),
        migrations.AlterModelOptions(
            name='analyticprofileviewsperdate',
            options={'verbose_name': 'Análise de visualização do perfil por data', 'verbose_name_plural': 'Análises de visualizações de perfis por data'},
        ),
    ]
